### ISSUE TITLE
Error:Could not read script '/home/ttnd/Downloads/vimeo-networking-java-1.1.0/stag-java/settings-parent.gradle' as it does not exist.

### ISSUE THREAD

**Issue by shivangbtech** [vimeo/vimeo-networking-java#106]
I am trying to build project but getting error:

Error:Could not read script '/home/ttnd/Downloads/vimeo-networking-java-1.1.0/stag-java/settings-parent.gradle' as it does not exist.

Found: stag-java is empty thats why getting error

Could you please guide me how to build the project that can work properly.

**Comment by kevinzetterstrom** [comment]
Sorry for the issue @shivangbtech ! 
stag-java is a library we are currently building, and will be open-sourced within the next few weeks. For the time being, please use the ```master``` branch, or include this library as a jcenter dependency rather than a submodule. I will leave this issue open until stag-java is open-sourced.

**Comment by kevinzetterstrom** [comment]
@shivangbtech [stag-java](https://github.com/vimeo/stag-java) is now open-sourced. You should be able to build the 1.1.0 branch now.
