### ISSUE TITLE
Native playback Video.files Deprecated

### ISSUE THREAD

**Issue by amank22** [vimeo/vimeo-networking-java#188]
#### Issue Summary
In native playback the docs specify to use:
```
Video video = ...; // obtain a video you own as described above
ArrayList<VideoFile> videoFiles = video.files;
```
But recent version shows it as deprecated. 
**What is the new way of doing it???**

**Comment by amank22** [comment]
I think I Got it. 
`video.download`
Still, do update the Readme.

**Comment by amank22** [comment]
`video.embed` is also deprecated.
Request you to update that too in readme.

**Comment by kevinzetterstrom** [comment]
Hi @amank22 please still use the `video.files` array, as you will also receive HLS `VideoFile` objects in that array, whereas `video.download` only has progressive files. Also, `video.download` will only have VideoFiles when you have allowed a Video to be downloadable. 

`video.files` is marked as `Deprecated` since in a future version we will no longer support it. We will end up moving to the `video.play`, but right now that is not open to the public. `video.embed` is also deprecated because [`video.play`](https://github.com/vimeo/vimeo-networking-java/blob/v2.0.0/vimeo-networking/src/main/java/com/vimeo/networking/model/playback/Play.java) has a much more robust [representation](https://github.com/vimeo/vimeo-networking-java/blob/v2.0.0/vimeo-networking/src/main/java/com/vimeo/networking/model/playback/embed/Embed.java). The current deprecation warnings are there as a courtesy that these will change in a future release.

Once `video.play` is officially the way to obtain VideoFiles, we will update the Readme.

**Comment by amank22** [comment]
Thanks for the brief description.

**Comment by thearith070** [comment]
Dear @kevinzetterstrom 
video.play return null. Why it would like this?
Thank you.
