### ISSUE TITLE
How to import use this library on my Java project ? 

### ISSUE THREAD

**Issue by valterhenrique** [vimeo/vimeo-networking-java#190]
#### Issue Summary
I would like to use this library to make requests on Vimeo API.

#### Reproduction Steps
Create a project Java project on Intellij, import this library, vimeo-netoworking-java and be able to found its classes/packages.

#### Expected Behavior
Find the classes and packages after the library has been imported.

#### Actual Behavior
Can't find the classes/packages on my application.

Please, I need help! For more information visit [here](http://stackoverflow.com/questions/42712011/how-to-add-a-library-using-gradle-on-intellij).

**Comment by kevinzetterstrom** [comment]
Hi @valterhenrique I responded to your [StackOverflow post](https://stackoverflow.com/questions/42712011/how-to-add-a-library-using-gradle-on-intellij/42727944#42727944). We built this library using gradle and recommend including the library as a gradle dependency. Since we don't use maven to build, we don't supply a recommended way to include the library in a maven project: this is something we can keep in mind for the future though! In the meantime, as the code is hosted on [Bintray](https://bintray.com/vimeo/maven/vimeo-networking), you can see how they suggest to include it in a maven POM:
```
<dependency>
  <groupId>com.vimeo.networking</groupId>
  <artifactId>vimeo-networking</artifactId>
  <version>1.1.0</version>
  <type>pom</type>
</dependency>
```

I hope this helps!

**Comment by valterhenrique** [comment]
Hi Kevin, thank you for you answer, I've answered you on SO as well :)
However, the problem still the same. I also created this new project and pushed to a new repository to better show my problem: https://github.com/valterhenrique/42712011

**Comment by kevinzetterstrom** [comment]
@valterhenrique we do not use maven to build this library, so unfortunately we can't offer you exact steps for including this in your maven project. I suggest checking out documentation from both JetBrains and Bintray. I also suggest looking through StackOverflow on how to include a dependency in a maven project.

https://www.jetbrains.com/help/idea/2016.3/maven.html

https://bintray.com/docs/usermanual/formats/formats_mavenrepositories.html
