### ISSUE TITLE
about api versioning and deprecated properties

### ISSUE THREAD

**Issue by galcyurio** [vimeo/vimeo-networking-java#231]
#### Issue Summary
I am worry about deprecated properties.
I know already created and closed issue about this topic. (#188 )

However, I cannot use Video.play property. It's just throws me NullPointerException.
So that I inevitably use this deprecated properties.

I don't want NullPointerException when api updated.
So I wrote the following code

````java
private void initVimeo() {
    Configuration.Builder builder = new Configuration.Builder(Constants.Vimeo.ACCESS_TOKEN.getValue())
            .setApiVersionString("3.2");
    VimeoClient.initialize(builder.build());
}
````

Is this right way? and what is best practice?

#### Reproduction Steps
N/A

#### Expected Behavior
N/A

#### Actual Behavior
N/A

**Comment by kevinzetterstrom** [comment]
Hi @galcyurio ,

Yes, you can set the API version string this way. Our API has recently made a change to allow any consumer of this library to use pre-released versions of our API. If you use version 3.3, you will get the `Play` object, which is not deprecated. There is one catch at the moment: you will need to use the `develop` branch which means including this library as a gradle submodule. 

In the coming weeks, we will remove the ability to set the API version so that all consumers of this library will use the same version that our official apps use. When this change is made, we will remove the deprecated classes and publish a new version of this library to jCenter.

The choice is up to you: you can use the `develop` branch of this library and set the version code to 3.3 to receive the Play representation, or you can wait a few weeks until we release a 2.0 of this library.

**Comment by galcyurio** [comment]
Thanks @kevinzetterstrom,
I'll wait a few weeks.
