### ISSUE TITLE
Calling fetchNetworkContent throws no such instance error

### ISSUE THREAD

**Issue by cabudies** [vimeo/vimeo-networking-java#260]
In my app, I want to show my private videos to user whosoever downloads the android application. As per the documentation, I have initialized VimeoClient with accessToken (taken from web interface http://developer.vimeo.com/apps). After initializing the VimeoClient (not making any object reference), I have called the fetchNetworkContent method. However, it's showing 'No VimeoClient instance'. Please help me out.

Points to be taken care of:
1. I have tried using a variable of VimeoClient and then calling VimeoClient.getInstance() method to it. But it again returns error. No such instance of VimeoClient.
2. I have even tried initializing the VimeoClient first with configuration (setting access token, client ID, client secret, redirect uri) and after that calling VimeoClient.getInstance() still no luck.
3. Even tried using only ClientID and Client Secret in configuration and then calling authorizeWithClientCredentials. I am able to login, it shows success message however, whenever, I am calling fetchNetworkContent method here, I am getting the 'No such instance of VimeoClient' again here.

**Comment by anthonycr** [comment]
Sorry for the delayed response.

Due to the design of the `VimeoClient` class, as long as you call `VimeoClient.initialize` before calling `VimeoClient.getInstance`, you will get a valid initialized instance. If you call `getInstance` before calling `initialize` you will get the assertion error saying that you need to configure the instance.

So the minimum code you need to set up the `VimeoClient` is as follows:
```java
final String clientId = // your app id here (gotten from dev website)
final String clientSecret = // your app secret here (gotten from dev website)
final String scope = // the scope given to your app (gotten from dev website)
final AccountStore accountStore = // implement the AccountStore interface to save accounts between network calls. You must implement this and at least implement it to save the VimeoAccount in memory (optionally you can save it to disk).
final Configuration.Builder configBuilder = new Configuration.Builder(clientId, 
                  clientSecret, 
                  scope, 
                  accountStore);

VimeoClient.initialize(configurationBuilder.build());

// Then use the instance
VimeoClient.getInstance().fetchNetworkContent(...);
```

If you're doing this and getting an exception, could you post the stacktrace you are seeing along with the code you're using to initialize (please **don't** post your API keys).

**Comment by cabudies** [comment]
Thanks. It would be great if this can be entered in the documentation.

**Comment by anthonycr** [comment]
Documentation is definitely unclear about this, I'll update it 👍
