### ISSUE TITLE
video.getPlay() returns null

### ISSUE THREAD

**Issue by LinkOut** [vimeo/vimeo-networking-java#275]
#### Issue Summary
As docs suggesting, i'm trying to get the Play object using: Play play = video.getPlay(); but this always returns null... 

Any suggestions? 

I've followed the docs correctly and i'm using a token auth..

Thanks

**Comment by howardrigberg** [comment]
The `Play` object is not currently publicly available. It is used internally by Vimeo. Our default readme is admittedly confusing since it does not point to the readme for the current public version of our library: v1.1.1. Your can review the appropriate version of the documentation here:

https://github.com/vimeo/vimeo-networking-java/tree/v1.1.1-release#how-do-i-play-a-video

If you have a PRO account, you should have access to an array of `VideoFile` objects for your *own* videos at `video.files`.  Otherwise, the only way to play a video is by using the `video.embed` which will give you an `Embed` object. Regardless of your account level, you can only play videos for other users using the `Embed` object.

**Comment by RobertJWChen** [comment]
Hi @howardrigberg ,

I have a pro account, and I followed the v1.1.1 readme document you mentioned to get the video_file
But the getPlay() return value and files were both null.
Does Vimeo remove the support for this function?

Thanks a lot!
Robert

**Comment by howardrigberg** [comment]
@RobertJWChen, as I mentioned above, the `Play` object is not yet publicly available from our library.

Did you follow the instructions listed here:
https://github.com/vimeo/vimeo-networking-java/tree/v1.1.1-release#native-playback

If so, did you make sure to provide the `video_links` scope during initialization? 

Be aware that you will only be able to use `getLink` from the `video.files` list for your *own* videos. You won't be able to get a video playback link for any videos other than your own.

**Comment by RobertJWChen** [comment]
@howardrigberg ,
I really appreciate your help. I found that my issue is caused by the authentication problem, so I generated a new access token in the app page and fixed the issue.

Thanks a lot for your help
Robert
