### ISSUE TITLE
How to get library SDK 2.0.0 and above

### ISSUE THREAD

**Issue by VortanaSay** [vimeo/vimeo-networking-java#468]
Hi,

From bintray, the current version is 1.1.3, and from JitPack I tried to get 2.0.1-233 but it doesn't have the network2 codes. So I looked at the commit for 2.0.1-233 and it is #386 which is way behinds the current pull request.

When will the codes for network2 package available ?

Thanks.

**Comment by anthonycr** [comment]
Hey, very sorry for the confusion. The versions are messed up in JitPack unfortunately, and we haven't had time to rectify it or update the documentation yet. You should ignore what JitPack shows as the latest version.

The good news is that you can get the new networking2 code from JitPack by using the latest tag found in https://github.com/vimeo/vimeo-networking-java/releases. At the time of writing this comment, that version is `2.0.0-alpha.74`. We haven't had a chance to remove the erroneous Git tags you are seeing in JitPack. Know that we use the latest alpha in our production app, the `-alpha` suffix is there because we haven't completed the documentation necessary to push it to "production."

Hope that helps, let me know if you have further questions.

**Comment by VortanaSay** [comment]
Thanks, @anthonycr, for the explanation.
