### ISSUE TITLE
how to use an Acess token with 2.0.0?

### ISSUE THREAD

**Issue by AurimasSikorskas** [vimeo/vimeo-networking-java#497]
Trying to migrate from 1.1.3 -> 2.0.0 but I can't seem to find a way how to use the app AccessToken in the v2 library version?

**Comment by anthonycr** [comment]
We're trying to encourage developers to authenticate on each client instance in order to obtain a different access token for each instance. This way if one instance of the app is misbehaving or one user of the app is abusing the token, all the other app instances and users wouldn't be affected if the token gets revoked. The example app shows how that sort of authentication can be done (using an auth grant, though you can also use other log in methods).

Of course, abuse of the token isn't always a concern, so if that's the case for you, there is an indirect way to inject a token directly.

The example app in this repo can be slightly modified to always use a specific token.

```kotlin
class TokenAccountStore(accessToken: String): AccountStore {
  private val account = VimeoAccount(accessToken = accessToken)
        
  override fun loadAccount(): VimeoAccount = account

  // We won't be supporting logging in
  override fun storeAccount(vimeoAccount: VimeoAccount) = Unit

  // We won't be supporting logging out
  override fun removeAccount() = Unit
}

val constantAccountStore = TokenAccountStore(YOUR_TOKEN)

val configuration = VimeoApiConfiguration.Builder(CLIENT_ID, CLIENT_SECRET, listOf(ScopeType.PUBLIC))
  .withAccountStore(constantAccountStore)
  .build()

// Initialize the authenticator instance with the configuration and the api client.
val authenticator = Authenticator(configuration)

val apiClient = VimeoApiClient(configuration, authenticator)
```

Using this, the same token will always be used to make requests! Just be careful not to use `Authenticator.logOut()` so your token remains valid.

**Comment by anthonycr** [comment]
I'll also add that using the above approach you don't actually need to provide the client ID and secret as they are used for authentication and you don't need to authenticate if you are hardcoding the token.

**Comment by anthonycr** [comment]
Version 2.0.0 is released and the documentation is updated. The support you're looking for is now in the library, so I'm going to close this issue. Feel free to re-open if the [README](https://github.com/vimeo/vimeo-networking-java/blob/develop/README.md) and [auth README](https://github.com/vimeo/vimeo-networking-java/blob/develop/auth/README.md) don't answer any questions you have.
