### ISSUE TITLE
jcenter() is deprecated

### ISSUE THREAD

**Issue by KostiantynPetrenko** [vimeo/vimeo-networking-java#501]
#### Issue Summary
A brief but thorough description of the issue.

#### Reproduction Steps
Detailed steps to reproduce the issue.

#### Expected Behavior
What do you expect to happen as a result of the reproduction steps?

#### Actual Behavior
What currently happens as a result of the reproduction steps?

**Comment by KostiantynPetrenko** [comment]
Specify the dependency in your build.gradle file (make sure jcenter() is included as a repository) - jcenter() is deprecated, please use mavenCentral()

**Comment by anthonycr** [comment]
Try using the newest version of the library, 2.0.0-alpha.94 from JitPack instead of the old 1.1.3 version. We'll have an updated README added publicly with info on how to use soon. For now, you can refer to the updated README in this commit (not merged yet) for more info: https://github.com/vimeo/vimeo-networking-java/blob/44058db2a7297f371897815e04d1714359242b99/README.md

Let me know if you have questions.

**Comment by anthonycr** [comment]
Version 2.0.0 is now available on jitpack and the readme is updated to reflect this.
